import Header from './Header'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* nav bar */}
        <Header />
        <div className="bg-orange-300 relative container mx-auto p-6 flex items-center justify-between">
          {/* meanu items */}
          <div className='flex space-x-6'>
            <a href='/' className='hover:text-rose-400'>Home</a>
            <a href='/posts' className='hover:text-rose-400'>Posts</a>
            <a href='/gallery' className='hover:text-rose-400'>Gallery</a>
            <a href='/contact'className='hover:text-rose-400'>Contact</a>
            <a href='/about' className='hover:text-rose-400'>About</a>
          </div>
        </div>
        {children}
        </body>
    </html>
  )
}
